/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package it.unibo.example

import com.mongodb.ConnectionString
import com.mongodb.MongoClientSettings
import com.mongodb.client.MongoClient
import com.mongodb.client.MongoClients
import com.mongodb.client.MongoCollection
import com.mongodb.client.MongoDatabase
import org.bson.Document


fun main() {
    val atlasConnectionString = ConnectionString("mongodb+srv://alchemist-user:alchemist-pwd@alchemist.ewxds.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
    val localhostConnectionString = ConnectionString("mongodb://admin:admin@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000")
    testingMongoDB(atlasConnectionString)
    testingMongoDB(localhostConnectionString)
}

private fun testingMongoDB(connectionString: ConnectionString) {
    val settings: MongoClientSettings = MongoClientSettings.builder()
        .applyConnectionString(connectionString)
        .build()
    val mongoClient: MongoClient = MongoClients.create(settings)
    val database: MongoDatabase = mongoClient.getDatabase("prova-db-2")
    val collectionName: String = "prova-collection-"+System.currentTimeMillis()
    database.createCollection(collectionName)
    val collection: MongoCollection<Document> = database.getCollection(collectionName)
    val documentName = Document("name","documentName")
    collection.insertOne(documentName)
}
